backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/media"
public_folder: "/media"

collections:
  - label: "Posts"
    name: "posts"
    folder: "src/pages/posts"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
