backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/media"
public_folder: "/media"

collections:
  - label: "Posts"
    name: "posts"
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    summary: "[{{year}}-{{month}}-{{day}}] {{title}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ"}
      - {label: "Updated Date", name: "updated", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "Comma-separated list of tags"}
      - {label: "Body", name: "body", widget: "markdown"}

  # NOT using nested folder collections as it's too restrictive.
  # Instead we are using Folder Collections Path to catch the files in sub-folders
  # Specifying a 'folder' field didn't work well - move the file manually later.
  - label: "Wiki"
    label_singular: "Wiki Page"
    name: wiki
    folder: "src/content/wiki"
    media_folder: "/public/media/wiki" # Astro can only take files from the /public folder
    public_folder: "/media/wiki"
    create: true
    path: "{{dirname}}/{{filename}}"     # this allows the CMS to find the file
    slug: "{{dirname}}/{{slug}}"         # used when saving new files
    summary: "{{title}} [{{dirname}}]"
    fields:
      #- {label: "Folder", name: "folder", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Site Settings"
    name: "site"
    files:
      - label: "About Us"
        name: "about"
        file: "src/site/about.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image, required: false}
      - label: "Locations"
        name: "locations"
        file: "src/site/locations.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}

      - label: "Configuration"
        name: "config"
        file: "src/site/config.json"
        fields:
          - {label: "Copyright Statement", name: copyright,widget: string, required: false}
          - {label: "Google Analytics Tag ID", name: gaTagId, widget: string, required: false}
